# Generated by Django 5.1.15 on 2026-04-09 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_import", "0002_alter_fileupload_file"),
        ("projects", "0035_project_admin_can_edit_and_more"),
        ("tasks", "0060_add_allow_skip_to_task"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskAssignment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assignment_type",
                    models.CharField(
                        choices=[
                            ("ANNOTATOR", "Annotator"),
                            ("REVIEWER", "Reviewer"),
                            ("FINAL_REVIEWER", "Final reviewer"),
                        ],
                        max_length=32,
                    ),
                ),
                ("is_active", models.BooleanField(db_default=True, default=True)),
                ("reason", models.CharField(blank=True, max_length=255, null=True)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("unassigned_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "task_assignment",
            },
        ),
        migrations.CreateModel(
            name="TaskReview",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "review_type",
                    models.CharField(
                        choices=[
                            ("REVIEW", "Review"),
                            ("FINAL_REVIEW", "Final review"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("FIXED_AND_APPROVED", "Fixed and approved"),
                            ("RETURNED", "Returned"),
                            ("REOPENED", "Reopened"),
                        ],
                        max_length=32,
                    ),
                ),
                ("review_round", models.IntegerField(db_default=0, default=0)),
                ("comment", models.TextField(blank=True, null=True)),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "task_review",
            },
        ),
        migrations.CreateModel(
            name="TaskReviewRejectLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_stage",
                    models.CharField(
                        choices=[
                            ("ANNOTATION", "Annotation"),
                            ("REVIEW", "Review"),
                            ("FINAL", "Final"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "to_stage",
                    models.CharField(
                        choices=[
                            ("ANNOTATION", "Annotation"),
                            ("REVIEW", "Review"),
                            ("FINAL", "Final"),
                        ],
                        max_length=32,
                    ),
                ),
                ("reason", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "task_review_reject_log",
            },
        ),
        migrations.CreateModel(
            name="TaskWorkflowLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_status", models.CharField(blank=True, max_length=32, null=True)),
                ("to_status", models.CharField(max_length=32)),
                ("action_type", models.CharField(max_length=64)),
                (
                    "operator_role",
                    models.CharField(blank=True, max_length=2, null=True),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "task_workflow_log",
            },
        ),
        migrations.AddField(
            model_name="annotation",
            name="annotation_role",
            field=models.CharField(
                blank=True,
                help_text="Role of the actor who produced this annotation version",
                max_length=2,
                null=True,
                verbose_name="annotation role",
            ),
        ),
        migrations.AddField(
            model_name="annotation",
            name="final_decision",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ACCEPTED", "Accepted"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                help_text="Final reviewer decision for this annotation version",
                max_length=32,
                verbose_name="final decision",
            ),
        ),
        migrations.AddField(
            model_name="annotation",
            name="is_current_version",
            field=models.BooleanField(
                db_default=True,
                default=True,
                help_text="Marks the latest active annotation version for the task workflow",
                verbose_name="is current version",
            ),
        ),
        migrations.AddField(
            model_name="annotation",
            name="review_decision",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ACCEPTED", "Accepted"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                help_text="Reviewer decision for this annotation version",
                max_length=32,
                verbose_name="review decision",
            ),
        ),
        migrations.AddField(
            model_name="annotation",
            name="source_annotation",
            field=models.ForeignKey(
                blank=True,
                help_text="Source annotation version from which this one derives",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="derived_annotations",
                to="tasks.annotation",
            ),
        ),
        migrations.AddField(
            model_name="annotation",
            name="workflow_node",
            field=models.CharField(
                choices=[
                    ("ANNOTATION", "Annotation"),
                    ("REVIEW", "Review"),
                    ("FINAL", "Final"),
                ],
                default="ANNOTATION",
                help_text="Workflow node that produced this annotation version",
                max_length=32,
                verbose_name="workflow node",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="annotation_submitted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="annotation submitted at"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="assigned_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="assigned at"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="current_annotation",
            field=models.ForeignKey(
                blank=True,
                help_text="Current active annotation version for workflow",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_for_tasks",
                to="tasks.annotation",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="current_annotator",
            field=models.ForeignKey(
                blank=True,
                help_text="Currently assigned annotator",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workflow_annotator_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="current_final_reviewer",
            field=models.ForeignKey(
                blank=True,
                help_text="Currently assigned admin/final reviewer",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workflow_final_reviewer_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="current_reviewer",
            field=models.ForeignKey(
                blank=True,
                help_text="Currently assigned reviewer",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workflow_reviewer_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="final_reviewed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="final reviewed at"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="is_workflow_locked",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="Business lock after final completion",
                verbose_name="workflow locked",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="reject_count",
            field=models.IntegerField(
                db_default=0,
                default=0,
                help_text="Number of times the task was rejected or returned",
                verbose_name="reject count",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="reopen_count",
            field=models.IntegerField(
                db_default=0,
                default=0,
                help_text="Number of times the completed task was reopened",
                verbose_name="reopen count",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="review_round",
            field=models.IntegerField(
                db_default=0,
                default=0,
                help_text="Incremented when task re-enters the review loop",
                verbose_name="review round",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="review_submitted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="review submitted at"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="workflow_completed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="workflow completed at"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="workflow_status",
            field=models.CharField(
                choices=[
                    ("UNASSIGNED", "Unassigned"),
                    ("PENDING_ANNOTATION", "Pending annotation"),
                    ("ANNOTATING", "Annotating"),
                    ("PENDING_REVIEW", "Pending review"),
                    ("REVIEWING", "Reviewing"),
                    ("REVIEW_REJECTED", "Review rejected"),
                    ("PENDING_FINAL_REVIEW", "Pending final review"),
                    ("FINAL_REVIEWING", "Final reviewing"),
                    ("FINAL_REJECTED", "Final rejected"),
                    ("COMPLETED", "Completed"),
                    ("REOPENED", "Reopened"),
                ],
                db_index=True,
                default="UNASSIGNED",
                help_text="Business workflow status for annotation-review-final review process",
                max_length=32,
                verbose_name="workflow status",
            ),
        ),
        migrations.AddIndex(
            model_name="annotation",
            index=models.Index(
                fields=["task", "is_current_version"],
                name="task_comple_task_id_531876_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="annotation",
            index=models.Index(
                fields=["workflow_node"], name="task_comple_workflo_e04930_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["workflow_status"], name="task_workflo_d634df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["current_annotator", "workflow_status"],
                name="task_current_0c5bbc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["current_reviewer", "workflow_status"],
                name="task_current_703499_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["current_final_reviewer", "workflow_status"],
                name="task_current_87424d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["current_annotation"], name="task_current_cfdb3b_idx"
            ),
        ),
        migrations.AddField(
            model_name="taskassignment",
            name="assigned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_task_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="taskassignment",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workflow_assignments",
                to="tasks.task",
            ),
        ),
        migrations.AddField(
            model_name="taskassignment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="taskreview",
            name="annotation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="tasks.annotation",
            ),
        ),
        migrations.AddField(
            model_name="taskreview",
            name="reviewed_annotation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="review_outputs",
                to="tasks.annotation",
            ),
        ),
        migrations.AddField(
            model_name="taskreview",
            name="reviewer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="taskreview",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="tasks.task",
            ),
        ),
        migrations.AddField(
            model_name="taskreviewrejectlog",
            name="operator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_review_reject_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="taskreviewrejectlog",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_reject_logs",
                to="tasks.task",
            ),
        ),
        migrations.AddField(
            model_name="taskreviewrejectlog",
            name="task_review",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reject_logs",
                to="tasks.taskreview",
            ),
        ),
        migrations.AddField(
            model_name="taskworkflowlog",
            name="annotation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workflow_logs",
                to="tasks.annotation",
            ),
        ),
        migrations.AddField(
            model_name="taskworkflowlog",
            name="operator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_workflow_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="taskworkflowlog",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workflow_logs",
                to="tasks.task",
            ),
        ),
        migrations.AddField(
            model_name="taskworkflowlog",
            name="task_review",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workflow_logs",
                to="tasks.taskreview",
            ),
        ),
        migrations.AddIndex(
            model_name="taskassignment",
            index=models.Index(
                fields=["task", "assignment_type", "is_active"],
                name="task_assign_task_id_b04b7a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="taskassignment",
            index=models.Index(
                fields=["user", "assignment_type", "is_active"],
                name="task_assign_user_id_1cedde_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="taskassignment",
            index=models.Index(
                fields=["assigned_by"], name="task_assign_assigne_e38594_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskreview",
            index=models.Index(
                fields=["task", "review_type", "review_round"],
                name="task_review_task_id_41e64c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="taskreview",
            index=models.Index(
                fields=["reviewer", "review_type"],
                name="task_review_reviewe_85b0bd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="taskreview",
            index=models.Index(
                fields=["annotation"], name="task_review_annotat_568deb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskreview",
            index=models.Index(
                fields=["reviewed_annotation"], name="task_review_reviewe_384921_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskreviewrejectlog",
            index=models.Index(fields=["task"], name="task_review_task_id_312bce_idx"),
        ),
        migrations.AddIndex(
            model_name="taskreviewrejectlog",
            index=models.Index(
                fields=["task_review"], name="task_review_task_re_2a79a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskreviewrejectlog",
            index=models.Index(
                fields=["operator"], name="task_review_operato_a75d72_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskworkflowlog",
            index=models.Index(
                fields=["task", "created_at"], name="task_workfl_task_id_be3074_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskworkflowlog",
            index=models.Index(
                fields=["operator", "created_at"], name="task_workfl_operato_727c7d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskworkflowlog",
            index=models.Index(
                fields=["task_review"], name="task_workfl_task_re_f58312_idx"
            ),
        ),
    ]
