# Generated by Django 5.1.15 on 2026-04-09 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0034_project_annotator_evaluation_enabled"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="admin_can_edit",
            field=models.BooleanField(
                db_default=True,
                default=True,
                help_text="Whether admin can modify final result directly",
                verbose_name="admin can edit",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="allow_final_reject_to_annotator",
            field=models.BooleanField(
                db_default=True,
                default=True,
                help_text="Whether final reviewer can reject directly back to annotator",
                verbose_name="allow final reject to annotator",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="allow_reopen_completed_task",
            field=models.BooleanField(
                db_default=True,
                default=True,
                help_text="Whether completed tasks can be reopened",
                verbose_name="allow reopen completed task",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="enable_final_review_stage",
            field=models.BooleanField(
                db_default=True,
                default=True,
                help_text="Whether admin final review step is enabled for the project",
                verbose_name="enable final review stage",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="enable_review_stage",
            field=models.BooleanField(
                db_default=True,
                default=True,
                help_text="Whether reviewer step is enabled for the project",
                verbose_name="enable review stage",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="reviewer_can_edit",
            field=models.BooleanField(
                db_default=True,
                default=True,
                help_text="Whether reviewer can modify annotation result directly",
                verbose_name="reviewer can edit",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="task_assignment_mode",
            field=models.CharField(
                choices=[
                    ("MANUAL", "Manual"),
                    ("HYBRID", "Hybrid"),
                    ("AUTO_FUTURE", "Auto future"),
                ],
                default="MANUAL",
                help_text="Task assignment mode for the project workflow",
                max_length=32,
                verbose_name="task assignment mode",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="workflow_enabled",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="Whether project uses explicit annotator-reviewer-admin workflow",
                verbose_name="workflow enabled",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="workflow_mode",
            field=models.CharField(
                choices=[
                    ("STANDARD", "Standard"),
                    ("SIMPLE_REVIEW", "Simple review"),
                    ("CUSTOM_FUTURE", "Custom future"),
                ],
                default="STANDARD",
                help_text="Business workflow mode for the project",
                max_length=32,
                verbose_name="workflow mode",
            ),
        ),
        migrations.CreateModel(
            name="ProjectMemberRole",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("OW", "Owner"),
                            ("AD", "Administrator"),
                            ("MA", "Manager"),
                            ("RE", "Reviewer"),
                            ("AN", "Annotator"),
                            ("VI", "Viewer"),
                        ],
                        help_text="Project-scoped role",
                        max_length=2,
                        verbose_name="role",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        help_text="User who granted the project role",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_project_member_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project_member",
                    models.ForeignKey(
                        help_text="Project member ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="projects.projectmember",
                    ),
                ),
            ],
            options={
                "db_table": "project_member_role",
                "indexes": [
                    models.Index(fields=["role"], name="project_mem_role_4bf2ab_idx"),
                    models.Index(
                        fields=["granted_by"], name="project_mem_granted_ab1de8_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project_member", "role"),
                        name="unique_project_member_role",
                    )
                ],
            },
        ),
    ]
